version: '3'
services:
 express-server: # Сервер Express
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: "mongodb://admin:admin@db:27018/mydatabase?authSource=admin&directConnection=true"
 db: # База данихх
    image: prismagraphql/mongo-single-replica:5.0.3
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
